'''
2 4 6 10 16 ... n
The above sequence is generated by adding the previous two numbers. 
Given n, find the nth number
'''

def addSeq(n, b1, b2):
    """
    Args:
     n(int32)
     b1(int32)
     b2(int32)
    Returns:
     int32
    """
    # Write your code here.
    if n == 1:
        return b1
    elif n == 2:
        return b2
    
    for i in range(3, n+1):
        next_num = b1 + b2
        b1 = b2
        b2 = next_num
        print(next_num, end=' ')
    print()    
    return next_num

addSeq(4, 2, 4)

def addSeqRecursive(n, b1, b2):
    """
    Args:
     n(int32)
     b1(int32)
     b2(int32)
    Returns:
     int32
    """
    # Write your code here.
    if n == 1:
        return b1
    elif n == 2:
        return b2
    
    return addSeqRecursive(n-1, b1, b2) + addSeqRecursive(n-2, b1, b2)

print(addSeqRecursive(4, 2, 4))


def fibonacci(n):
    """
    Args:
     n(int32)
    Returns:
     int32
    """
    # Write your code here.
    if n == 1:
        return 0
    elif n == 2:
        return 1
    
    return fibonacci(n-1) + fibonacci(n-2)

def fibonacciIterative(n):
    """
    Args:
     n(int32)
    Returns:
     int32
    """
    # Write your code here.
    if n == 1:
        return 0
    elif n == 2:
        return 1
    
    a, b = 0, 1
    for i in range(3, n+1):
        a, b = b, a+b
    return b

print(fibonacciIterative(4))

def fibonacciMemo(n, memo=None):
    """
    Args:
     n(int32)
    Returns:
     int32
    """
    # Write your code here.
    if memo is None:
        memo = {}

    if n in memo:
        return memo[n]
    
    if n == 1:
        return 0
    elif n == 2:
        return 1
    
    memo[n] = fibonacciMemo(n-1, memo) + fibonacciMemo(n-2, memo)
    return memo[n]

print(fibonacciMemo(4))